### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by ZaddesXy** [9P9/Discord-QR-Token-Logger#10]
[?] Awaiting Page to Load!
[*] Page loaded.
Traceback (most recent call last):
  File "C:\Users\akars\OneDrive\Masaüstü\Discord-QR-Token-Logger-main\qr_generator.py", line 99, in <module>
    main()
  File "C:\Users\akars\OneDrive\Masaüstü\Discord-QR-Token-Logger-main\qr_generator.py", line 49, in main
    qr_code = div.find('img')['src']
AttributeError: 'NoneType' object has no attribute 'find'
Press any key to continue . . .

**Comment by Bardia-SG** [comment]
same here

**Comment by JayOrez81** [comment]
Change line 48 to  div = soup.find('div', {'class': 'qrCode-2R7t9S'}) and it should fix it. I assume discord just updated class name which caused the code to stop working.

**Comment by ThatTSGuy** [comment]
Use the improved one, without Selenium: https://github.com/ThatTSGuy/discord-qr-token-grabber
