### ISSUE TITLE
Help pls :D

### ISSUE THREAD

**Issue by mayerbalint** [9P9/Discord-QR-Token-Logger#2]
Traceback (most recent call last):
  File "D:\Mayer Bálint\Desktop\asd\qr_generator.py", line 99, in <module>
    main()
  File "D:\Mayer Bálint\Desktop\asd\qr_generator.py", line 37, in main
    driver = webdriver.Chrome(options=options, executable_path=r'chromedriver.exe')
  File "C:\Users\Mayer Bálint\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Mayer Bálint\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Mayer Bálint\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Mayer Bálint\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Mayer Bálint\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 89
Current browser version is ------------- with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

**Comment by Cleboost** [comment]
Same error !

**Comment by caninerhino4779** [comment]
same

**Comment by NBG999** [comment]
same, pls heeeelp

**Comment by KAMLEGENDZ** [comment]
just use the last chromedriver.exe

**Comment by Jacuhb** [comment]
you have to get an up to date chromedriver.exe and then replace it in the folder

**Comment by bilalraj3232** [comment]
same error

**Comment by the-cult-of-integral** [comment]
Try [this fork](https://github.com/the-cult-of-integral/Discord-QR-Token-Logger). This fork includes compatible browser and chrome driver in the same directory.
