### ISSUE TITLE
Doesnt generate the qr code

### ISSUE THREAD

**Issue by PetriJokinen** [9P9/Discord-QR-Token-Logger#65]
- [ x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)

**Failure Logs**

Exception in thread Thread-1 (main): Traceback (most recent call last): File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1038, in _bootstrap_inner self.run() File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 975, in run self._target(*self._args, **self._kwargs) File "C:\Users\vonk\Downloads\Discord image qr code logger\Discord-QR-Token-Logger-main\Discord-QR-Token-Logger\main.py", line 91, in main qr_code = qrg.get_qr_from_source(source) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\vonk\Downloads\Discord image qr code logger\Discord-QR-Token-Logger-main\Discord-QR-Token-Logger\discord_token.py", line 25, in get_qr_from_source qr_code = div.find('img')['src'] ~~~~~~~~~~~~~~~^^^^^^^ TypeError: 'NoneType' object is not subscriptable

**Comment by the-cult-of-integral** [comment]
Unable to reproduce it on my machine. What is your default browser?

**Comment by PetriJokinen** [comment]
> Unable to reproduce it on my machine. What is your default browser?

google chrome, and my OS is windows 10 education

**Comment by mouadessalim** [comment]
This issue doesn't follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/main/CONTRIBUTING.md). Thank you for updating the issue, in case of no change the issue **_may be closed_**. Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/9P9/Discord-QR-Token-Logger/blob/main/CODE_OF_CONDUCT.md).

**The issue doesn't respect this instruction:**
https://github.com/9P9/Discord-QR-Token-Logger/blob/3adf814c7fc8a04da294f200ee288803648bef4b/CONTRIBUTING.md?plain=1#L52

The error being logged by Python is due to Selenium's inability to locate `div.find('img')['src']`. This outcome is reasonable, given that Discord has updated the source code of their web page, and thus the element cannot be found. However, I had already fixed this bug a long time ago. You simply need to use the latest version of the program.

**D'ONT FORGET BEFORE USING THE LAST VERSION TO FOLLOW THE README FILE & TO INSTALL ALL DEPENDENCIES !**

@PetriJokinen

**Comment by loggerbeamtest** [comment]
lol not even exist
fake!!111!!!

**Comment by mouadessalim** [comment]
This repository has been archived and is no longer maintained. Please note that no further updates or support will be provided.
