### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by WOLFIEHOLZ** [9P9/Discord-QR-Token-Logger#67]
**Prerequisites**

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ Y] I am running the latest version
- [Y ] I checked the documentation and found no answer
- [Y ] I checked to make sure that this issue has not already been filed
- [N ] I'm reporting the issue to the correct repository (for multi-repository projects)

**Expected Behavior**
When i run the main it should open 

**Current Behavior**

Traceback (most recent call last):
  File "C:\Users\lewis\Documents\Discord-QR-Token-Logger-main\Discord-QR-Token-Logger\main.py", line 35, in <module>
    from cairosvg import svg2png
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python311\Lib\site-packages\cairosvg\__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python311\Lib\site-packages\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python311\Lib\site-packages\cairocffi\__init__.py", line 47, in <module>
    cairo = dlopen(
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python311\Lib\site-packages\cairocffi\__init__.py", line 44, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

**Failure Information (for bugs)**

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

**Steps to Reproduce**

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

**Context**

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Firmware Version:
* Operating System:
* SDK version:
* Toolchain version:

**Failure Logs**

Traceback (most recent call last):
  File "C:\Users\lewis\Documents\Discord-QR-Token-Logger-main\Discord-QR-Token-Logger\main.py", line 35, in <module>
    from cairosvg import svg2png
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python311\Lib\site-packages\cairosvg\__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python311\Lib\site-packages\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python311\Lib\site-packages\cairocffi\__init__.py", line 47, in <module>
    cairo = dlopen(
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python311\Lib\site-packages\cairocffi\__init__.py", line 44, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

**Comment by mouadessalim** [comment]
This issue doesn't follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/main/CONTRIBUTING.md). Thank you for updating the issue, in case of no change the issue **_may be closed_**. Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/9P9/Discord-QR-Token-Logger/blob/main/CODE_OF_CONDUCT.md).

**The issue doesn't respect this instruction:**
https://github.com/9P9/Discord-QR-Token-Logger/blob/6518a9d6efe43a046e4bf8a11ee1cc1aa7103680/CONTRIBUTING.md?plain=1#L29

https://github.com/9P9/Discord-QR-Token-Logger/blob/6518a9d6efe43a046e4bf8a11ee1cc1aa7103680/README.md?plain=1#L97

@WOLFIEHOLZ

**Comment by jayambe36** [comment]
It looks like the issue is caused by a missing library called "cairo" or "cairo-2". This library is required by the cairosvg package which is being imported by the main.py file in your project.

You may need to install the Cairo graphics library on your system. You can do this by following the installation instructions for your operating system:

    For Windows: You can download the precompiled binaries from https://www.lfd.uci.edu/~gohlke/pythonlibs/#pycairo. Choose the appropriate version of the library based on your Python version and system architecture, and then install it using pip: pip install <path_to_wheel_file>
    For Linux: You can install the library using your package manager. For example, on Ubuntu, you can run sudo apt-get install libcairo2-dev to install the library and its development files.
    For macOS: You can install the library using Homebrew: brew install cairo.

Once you have installed the library, try running your code again to see if the issue has been resolved.

**Comment by mouadessalim** [comment]
@jayambe36 yes exactly and this is why he need to install dependencies, i've done everything correctly, people just need to follow the instructions, this is why he need to install GTK3 runtime that contain the missing dll's files.

https://github.com/9P9/Discord-QR-Token-Logger/blob/6518a9d6efe43a046e4bf8a11ee1cc1aa7103680/README.md?plain=1#L97

**Comment by PetriJokinen** [comment]
I am receiving the same problem. And reinstalling GTK3 and pycairo, cairocffi and cairosvg doesnt help
